export const LOAD_COMMENT_LIST_REQUEST = 'LOAD_COMMENT_LIST_REQUEST';
export const LOAD_COMMENT_LIST_SUCCESS = 'LOAD_COMMENT_LIST_SUCCESS';
export const LOAD_COMMENT_LIST_FAILURE = 'LOAD_COMMENT_LIST_FAILURE';

export const SUBMIT_COMMENT_REQUEST = 'SUBMIT_COMMENT_REQUEST';
export const SUBMIT_COMMENT_SUCCESS = 'SUBMIT_COMMENT_SUCCESS';
export const SUBMIT_COMMENT_FAILURE = 'SUBMIT_COMMENT_FAILURE';
