export const LOAD_COMMENT_LIST_REQUEST = 'LOAD_COMMENT_LIST_REQUEST';
export const LOAD_COMMENT_LIST_SUCCESS = 'LOAD_COMMENT_LIST_SUCCESS';
export const LOAD_COMMENT_LIST_FAILURE = 'LOAD_COMMENT_LIST_FAILURE';

export const LOAD_USER_COMMENT_VOTES_REQUEST = 'LOAD_USER_COMMENT_VOTES_REQUEST';
export const LOAD_USER_COMMENT_VOTES_SUCCESS = 'LOAD_USER_COMMENT_VOTES_SUCCESS';
export const LOAD_USER_COMMENT_VOTES_FAILURE = 'LOAD_USER_COMMENT_VOTES_FAILURE';

export const SUBMIT_COMMENT_REQUEST = 'SUBMIT_COMMENT_REQUEST';
export const SUBMIT_COMMENT_SUCCESS = 'SUBMIT_COMMENT_SUCCESS';
export const SUBMIT_COMMENT_FAILURE = 'SUBMIT_COMMENT_FAILURE';

export const UPVOTE_COMMENT_SUCCESS = 'UPVOTE_COMMENT_SUCCESS';
export const UPVOTE_COMMENT_FAILURE = 'UPVOTE_COMMENT_FAILURE';

export const DOWNVOTE_COMMENT_SUCCESS = 'DOWNVOTE_COMMENT_SUCCESS';
export const DOWNVOTE_COMMENT_FAILURE = 'DOWNVOTE_COMMENT_FAILURE';

export const REMOVE_VOTE_FROM_COMMENT = 'REMOVE_VOTE_FROM_COMMENT';
