export const LOAD_POST_LIST_REQUEST = 'LOAD_POST_LIST_REQUEST';
export const LOAD_POST_LIST_SUCCESS = 'LOAD_POST_LIST_SUCCESS';
export const LOAD_POST_LIST_FAILURE = 'LOAD_POST_LIST_FAILURE';

export const SUBMIT_POST_REQUEST = 'SUBMIT_POST_REQUEST';
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS';
export const SUBMIT_POST_FAILURE = 'SUBMIT_POST_FAILURE';

export const LOAD_TEAM_MEMBERS_REQUEST = 'LOAD_TEAM_MEMBERS_REQUEST';
export const LOAD_TEAM_MEMBERS_SUCCESS = 'LOAD_TEAM_MEMBERS_SUCCESS';
export const LOAD_TEAM_MEMBERS_FAILURE = 'LOAD_TEAM_MEMBERS_FAILURE';

export const LOAD_USER_VOTES_REQUEST = 'LOAD_USER_VOTES_REQUEST';
export const LOAD_USER_VOTES_SUCCESS = 'LOAD_USER_VOTES_SUCCESS';
export const LOAD_USER_VOTES_FAILURE = 'LOAD_USER_VOTES_FAILURE';

export const SET_POST_FEED_FILTER = 'SET_POST_FEED_FILTER';

export const postFeedFilters = {
  MOST_RECENT: 'MOST_RECENT',
  TOP_VOTED: 'TOP_VOTED',
}
