export const LOAD_POST_LIST_REQUEST = 'LOAD_POST_LIST_REQUEST';
export const LOAD_POST_LIST_SUCCESS = 'LOAD_POST_LIST_SUCCESS';
export const LOAD_POST_LIST_FAILURE = 'LOAD_POST_LIST_FAILURE';

export const SUBMIT_POST_REQUEST = 'SUBMIT_POST_REQUEST';
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS';
export const SUBMIT_POST_FAILURE = 'SUBMIT_POST_FAILURE';
