export const UPVOTE_POST_SUCCESS = 'UPVOTE_POST_SUCCESS';
export const UPVOTE_POST_FAILURE = 'UPVOTE_POST_FAILURE';

export const DOWNVOTE_POST_SUCCESS = 'DOWNVOTE_POST_SUCCESS';
export const DOWNVOTE_POST_FAILURE = 'DOWNVOTE_POST_FAILURE';

export const REMOVE_VOTE_FROM_POST = 'REMOVE_VOTE_FROM_POST';

export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE';
