export const GET_USER_TEAMS_REQUEST = 'GET_USER_TEAMS_REQUEST';
export const GET_USER_TEAMS_SUCCESS = 'GET_USER_TEAMS_SUCCESS';
export const GET_USER_TEAMS_FAILURE = 'GET_USER_TEAMS_FAILURE';

export const TOGGLE_COLOR_THEME = 'TOGGLE_COLOR_THEME';
